Swift 3.0 support
IB2016/Snappy pull request #1
Opened 2016-10-11 12:25 UTC by PChmiel

Updated to Swift 3.0, added tests for API methods

2016-10-11 14:29 UTC, sunshinejr requested changes
👌 just a few minor comments

2016-10-11 14:29 UTC, sunshinejr commented on Snappy/ImagesViewController.swift
> +        refreshControl?.backgroundColor = UIColor.white
here we can even skip the `UIColor`, with just `.white` (below as well)

2016-10-11 14:29 UTC, sunshinejr commented on Snappy/ImagesViewController.swift
> +        cell.textLabel?.text = images[(indexPath as NSIndexPath).row]
is the cast to `NSIndexPath` needed here? genuine question, not sure

2016-10-11 14:29 UTC, sunshinejr commented on Snappy/PhotoViewController.swift
> +        flashButton.setImage(UIImage(named: currentFlashMode ? "FlashButtonImage" : "FlashOffButtonImage"), for: UIControlState())
`.normal` instead of `UIConstrolState()`

2016-10-11 14:29 UTC, sunshinejr commented on Snappy/SnappyAPI.swift
> +       Alamofire.upload(multipartFormData: { (multipartData) in
this closure with `multipartData` could be extracted before `Alamofire.upload`, to make it more readable (yeah, this on the left is not readable either :D)

2016-10-11 14:29 UTC, sunshinejr commented on SnappyAPITests/SnappyAPITests.swift
> +                expectationGetAllImages.fulfill()
hmm, maybe move it after the switch? in failure case it doesn't get fulfilled and waits for response

2016-10-12 07:41 UTC, PChmiel commented
@sunshinejr thx for cr, code upadted

2016-10-12 11:46 UTC, sunshinejr commented on Snappy/SnappyAPI.swift
> +        Alamofire.upload(multipartFormData: { (multipartData) in
hmm, isn't it working with just:
```
Alamofire.upload(mulitpartFormData: multipartDataClosure, to: ...
```
?

2016-10-12 11:59 UTC, PChmiel commented
@sunshinejr should be better now;)

2016-10-12 12:01 UTC, sunshinejr approved these changes
👏

2016-10-12 12:02 UTC, merged