Improved tests
IB2016/Snappy pull request #2
Opened 2016-10-21 11:06 UTC by PChmiel

2016-10-24 15:28 UTC, sunshinejr requested changes

2016-10-24 15:28 UTC, sunshinejr commented on Podfile
> +        pod 'OHHTTPStubs/Swift'
space to be removed 🤓 + probably we can remove 2 stubs pods and use one (but I might be wrong): 

```
pod 'OHHTTPStubs/Swift'
```

2016-10-24 15:28 UTC, sunshinejr commented on Podfile
> +	pod 'OHHTTPStubs/Swift'
same here, I also wonder if we can define "libraries" and use them both here and in normal target, as I messaged you on slack some time ago, example: https://github.com/Moya/Moya/blob/master/Demo/Podfile

2016-10-24 15:28 UTC, sunshinejr commented on Snappy/PhotoViewController.swift
> +    lazy var switchCameraCompletion : ((UIView?) -> ()) = {
line before should be inline with "{"

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +                case .success(_):
`.success` instead of `success(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +                case .failure(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +            case .failure(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +                case .success(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +                case .failure(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +                }
`else { expectation.fulfill() }` in case there is result but the image is not there

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +        XCTAssertEqual(SnapchatAPIConstants.URL.getImages(forUser: 11),"https://snappytestapp.herokuapp.com/images/get/11")
space after `,` needed 🤓

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +        let str : Result<Any> = Result.failure(error)
`let str: Result<Any>`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +        // Put teardown code here. This method is called after the invocation of each test method in the class.
we can remove this comment as well

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +    override func setUp() {
this method is not needed probably, so we can remove it

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +
there is an empty line, is this done for readability?

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +            case .success(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +            case .failure(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +
2 empty lines not needed here

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +                default:
`default: ()`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +        let exp = expectation(description: "upload image with 400 error")
let's use full `expectation` instead of `exp`, as in the other tests

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +        let exp = expectation(description: "upload image with no error")
let's use full `expectation` instead of `exp`, as in the other tests

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +                    XCTAssertEqual(response.value.debugDescription, "Optional({\n    Success = \"Image uploaded correctly.\";\n})")
should it be before `fulfill`? Also, this assert seems really weird with this text:
```
Optional({\n    Success = \"Image uploaded correctly.\";\n})
```

maybe we can find another way to check it? parse to json dict and check both "Success" keys?

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +                default:
`default: ()`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/APIWithStubsTests.swift
> +                case .success(_):
same, remove `(_)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/CameraManagerTests.swift
> +    override func setUp() {
missing empty line between `previewSize` and `setUp` but I think the `setUp` & `tearDown` are not needed here as well so we can remove them both

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/CameraManagerTests.swift
> +        let exp = expectation(description: "take photo")
same, `expectation`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/CameraManagerTests.swift
> +            if let image = image {
how about:
```swift
XCTAssertTrue(image?.size.width > 1000)
```

without ifs? because if there is no image, there is no assert as well

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/CameraManagerTests.swift
> +        if let device = (CameraManager.session!.inputs.first as! AVCaptureDeviceInput).device {
let's use `?` instead of `!` in `if let` + this test is only executed when 2 checks passes, it has to assert even tho the checks don't pass

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/CameraManagerTests.swift
> +        let exp = expectation(description: "front camera")
`expectation`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/CameraManagerTests.swift
> +        if let camera = CameraManager.session?.inputs.first as? AVCaptureDeviceInput {
same as https://github.com/DroidsOnRoids/Snappy/pull/2/files#diff-b8e6e68c343069854deae9386fd14723R56

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +        // Put setup code here. This method is called before the invocation of each test method in the class.
comment not needed

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +    override func tearDown() {
method not needed

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +        if let firstSubview = viewController?.view.subviews.first {
https://github.com/DroidsOnRoids/Snappy/pull/2/files#diff-b8e6e68c343069854deae9386fd14723R56

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +            XCTAssertFalse((viewController.view.subviews.contains(lastSubview)))
double parenthesis probably not needed here, please check everywhere where it is needed and where it is not

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +        guard let viewController = viewController else { XCTAssert(false) ; return }
let's move it below, this `;` really scares me off 😱 
also, you can try with `XCTFail` instead of `XCTAssert(false)`

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +class MockCameraManager: CameraManagerProtocol {
let's move it to another file, also one empty line between `{` and parameters

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +
empty line to remove

2016-10-24 15:28 UTC, sunshinejr commented on SnappyAPITests/PhotoViewControllerTests.swift
> +
empty line to remove

2016-10-25 07:10 UTC, PChmiel commented on SnappyAPITests/APITests.swift
> +        let str : Result<Any> = Result.failure(error)
The question is which is better? Keep it as it is or replace it by Result.failure(error) as Result<Any>

2016-10-25 07:39 UTC, sunshinejr commented on SnappyAPITests/APITests.swift
> +        let str : Result<Any> = Result.failure(error)
I've mean't that there is a space between `str` and `:`, that is not needed

2016-10-25 07:51 UTC, PChmiel commented on SnappyAPITests/CameraManagerTests.swift
> +            if let image = image {
I can't use ? operator here, ! or if let only

2016-10-31 08:33 UTC, PChmiel commented
@sunshinejr ready for CR

2016-11-08 19:37 UTC, merged